<template>
  <aside class="widget widget-categories box-shadow mb-30">
    <h5 class="widget-title border-left mb-10">Warengruppen</h5>
    <div id="cat-treeview" class="product-cat">
      <ul>
        <li>
          <a
            href="https://www.aventura-print.de/abiturzeitung-bestellen,category,13391.html"
            >Abiturzeitung</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/aktenordner-mit-2-loch-hebelmechanik-und-schlitz-drucken-lassen,category,14084.html"
            >Aktenordner</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/ansteckbuttons-drucken-lassen,category,18902.html"
            >Ansteckbuttons</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/architektenzeichnungen-drucken-lassen,category,15139.html"
            >Architekten-Zeichnungen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/aufkleber-ettiketten-drucken-lassen,category,9838.html"
            >Aufkleber &amp; Ettiketten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/beachflag-bedrucken-lassen,category,17339.html"
            >Beachflag</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/bedruckte-glaeser,category,19513.html"
            >Bedruckte Gläser</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/bedruckte-tassen-foto,category,16668.html"
            >Bedruckte Tassen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/behelfsmaske-online-drucken-lassen,category,22877.html"
            >Behelfsmaske</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/umweltfreundliche-druckprodukte,category,28246.html"
            >Besonders umweltfreundliche Druckprodukte</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/bierdeckel-bedrucken-lassen,category,10108.html"
            >Bierdeckel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/bloecke-drucken-lassen,category,9473.html"
            >Blöcke</a
          >
        </li>
        <li>
          <a href="https://www.aventura-print.de/branchen,category,28235.html"
            >Branchen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/briefbogen-drucken-lassen,category,9466.html"
            >Briefbogen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/broschueren-und-magazine-drucken-lassen,category,13266.html"
            >Broschüren &amp; Magazine</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/buecher-drucken-lassen,category,12529.html"
            >Bücher</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/calanda-broncos-fanartikel-online-bestellen,category,27062.html"
            >Calanda Broncos Fanartikel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/diplomarbeiten-drucken-lassen,category,13847.html"
            >Diplomarbeiten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/exklusive-duft-lack-produkte-drucken-lassen,category,13777.html"
            >Duftlack Veredelung</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/ehrungen-drucken-lassen,category,20291.html"
            >Ehrungen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/einlassbaender-online-drucken,category,20554.html"
            >Einlassbänder</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/einschlagpapier-online-bedrucken,category,27482.html"
            >Einschlagpapier</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/eintrittskarten,category,9486.html"
            >Eintrittskarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/etiketten-online-bedrucken,category,24047.html"
            >Etiketten &amp; Sticker</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/faltplaner-online-drucken-lassen,category,19976.html"
            >Faltplaner</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/fanklatsche-bedrucken-lassen,category,19896.html"
            >Fanklatschen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/pflegetuecher-online-drucken-lassen,category,20547.html"
            >Feuchtpflegetücher</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/fine-art-printing-online-bedrucken,category,28252.html"
            >Fine Art Printing</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/firmenstempel-drucken-lassen,category,13567.html"
            >Firmenstempel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/flaschenhaenger-drucken-lassen,category,20928.html"
            >Flaschenhänger</a
          >
        </li>
        <li>
          <router-link to="/flyer">Flyer &amp; Folder</router-link>
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/folie-drucken-lassen,category,19152.html"
            >Foliendruck</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/foto-geschenke-drucken-lassen,category,19359.html"
            >Foto-Geschenke</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/fototapeten-drucken-lassen,category,15140.html"
            >Fototapeten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/weingummi-online-drucken,category,18708.html"
            >Fruchtgummi</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/getraenke-flaschen-extrem-guenstig-bestellen,category,21915.html"
            >Getränke Flaschen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/getraenke-karten-online-bestellen,category,9448.html"
            >Getränke-Karten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/grusskarten-einladungskarten,category,9485.html"
            >Gruß- &amp; Einladungskarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/gruener-hintergrund-roll-ups-faltdisplays-online-bedrucken,category,27212.html"
            >Grüner Hintergrund Roll-Ups &amp; Faltdisplays</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/haftquader-haftnotizen-online-drucken,category,18736.html"
            >Haftquader / Haftnotizen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/handyschutzhuelle-online-drucken,category,18678.html"
            >Handyschutzhülle</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/hissflagen-schnell-und-preiswert,category,15252.html"
            >Hissflaggen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/hochzeitskarten-drucken-lassen,category,13928.html"
            >Hochzeitskarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/hochzeitszeitungen-bestellen,category,13416.html"
            >Hochzeitszeitungen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/huellen-fuer-karten-online-bestellen,category,22048.html"
            >Hüllen für Karten</a
          >
        </li>
        <li>
          <a href="https://www.aventura-print.de/kalender,category,9487.html"
            >Kalender</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/karten-zu-ostern-drucken-lassen,category,14764.html"
            >Karten zu Ostern</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/karten-zum-geburtstag-drucken-lassen,category,14675.html"
            >Karten zum Geburtstag</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/klemmbrett-online-bedrucken,category,17925.html"
            >Klemmbrett</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/kopierpapier-guenstig-a4,category,16310.html"
            >Kopierpapier A4</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/briefumschlaege-drucken-lassen,category,9470.html"
            >Kuvertierhüllen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/leuchtkastenfolie-drucken-lassen,category,9769.html"
            >Leuchtkastenfolie</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/loseblattsammlung-online-drucken,category,17408.html"
            >Loseblattsammlung</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/luftballon-bedrucken,category,19405.html"
            >Luftballon</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/magnetschilder-drucken-lassen,category,13780.html"
            >Magnetschilder</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/mailing-fuer-postkarten-drucken-lassen,category,18365.html"
            >Mailing für Postkarten</a
          >
        </li>
        <li>
          <a href="https://www.aventura-print.de/mailings,category,10697.html"
            >Mailings</a
          >
        </li>
        <li>
          <a href="https://www.aventura-print.de/messe,category,28243.html"
            >Messe</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/meterstaebe-online-drucken-lassen,category,18675.html"
            >Meterstäbe</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/foto-mousepad-online-druckerei,category,17659.html"
            >Mousepads inkl. Druck</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/mundtuecher-online-bedrucken,category,24423.html"
            >Mundtücher</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/notizbuch-online-bedrucken-lassen,category,18367.html"
            >Notizbuch</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/paketklebebaender-online-bestellen,category,24198.html"
            >Paketklebebänder</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/pappbecher-und-zubehoer-bestellen,category,21116.html"
            >Pappbecher &amp; Zubehör</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/plastikkarten,category,12255.html"
            >Plastikkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/platzdeckchen-mit-foto-online-gestalten,category,16755.html"
            >Platzdeckchen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/polo-shirts-online-bestellen,category,19181.html"
            >Polo-Shirts</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/poster-plakate,category,9176.html"
            >Poster &amp; Plakate</a
          >
        </li>
        <li>
          <a href="https://www.aventura-print.de/postkarten,category,9484.html"
            >Postkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/pressemappen-drucken-lassen,category,14041.html"
            >Pressemappen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/printklassiker-online-bedrucken,category,28643.html"
            >Printklassiker</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/private-label-drinks-online-bestellen,category,15820.html"
            >Private-Label-Drinks</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/praegezange-online-bestellen,category,24184.html"
            >Prägezangen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/praesentationsmappen-bedrucken,category,9418.html"
            >Präsentationsmappen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/rabattcoupons-online-bestellen,category,22076.html"
            >Rabattcoupons</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/ringbuecher-ordner,category,13308.html"
            >Ringbücher &amp; Ordner</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/rollen-etiketten-online-druckerei,category,17017.html"
            >Rollen-Etiketten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/rubbelkarten-drucken-lassen,category,14223.html"
            >Rubbelkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/schluesselbander-online-bestellen,category,19153.html"
            >Schlüsselbänder bedruckt</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/schreibtischunterlagen,category,9518.html"
            >Schreibtischunterlagen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/schuelerzeitung-bestellen,category,13395.html"
            >Schülerzeitung</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/selbstdurchschreibesaetze-drucken,category,9478.html"
            >Selbstdurchschreibesätze</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/snowflags-bedrucken-lassen,category,19768.html"
            >Snowflag</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/sommerartikel,category,28241.html"
            >Sommerartikel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/speise-karten-online-bestellen,category,18909.html"
            >Speise-Karten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/sticker-boegen-online-drucken-lassen,category,19860.html"
            >Sticker-bögen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/suesse-werbung-bestellen,category,19372.html"
            >Süßwaren</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/t-shirts-bedrucken,category,15876.html"
            >T-Shirts</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/tablettauflagen-online-bedrucken,category,28149.html"
            >Tablettauflagen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/zeitungen-online-bestellen,category,23508.html"
            >Tageszeitungen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/tapetenvlies-rollen-einfach-online-bestellen,category,18920.html"
            >Tapetenvlies</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/taschen-und-beutel-drucken-lassen,category,20443.html"
            >Taschen und Beutel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/taufkarten-drucken-lassen,category,13959.html"
            >Taufkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/bedruckte-und-bestickte-textilien-und-bekleidung,category,19155.html"
            >Textilien und Bekleidung</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/textilspannrahmen-drucken-lassen,category,19903.html"
            >Textilspannrahmen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/thekenaufsteller-tischaufsteller,category,9465.html"
            >Theken- &amp; Tischaufsteller</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/trauerkarten-drucken-lassen,category,14010.html"
            >Trauerkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/treuekarten-stempelkarten-drucken-lassen,category,18637.html"
            >Treuekarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/tuerhaenger-drucken-lassen,category,13557.html"
            >Türhänger</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/unterlagen-briefwahl-online-bedrucken,category,27589.html"
            >Unterlagen für Briefwahl</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/urkunden-online-bestellen,category,23634.html"
            >Urkunden</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/veranstaltungsplakate-drucken-lassen,category,18578.html"
            >Veranstaltungsplakate</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/verpackungen,category,18091.html"
            >Verpackungen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/visitenkarten-drucken,category,9179.html"
            >Visitenkarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/wahlplakate,category,17958.html"
            >Wahlplakate</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/wahlzettel-online-bedrucken,category,24901.html"
            >Wahlzettel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/weihnachtskarten-drucken-lassen,category,13775.html"
            >Weihnachtskarten</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/werbemittel-bestellen,category,18219.html"
            >Werbemittel</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/werbeplane-drucken-sparen-sie-bis-zu-80-beim-druck,category,13424.html"
            >Werbeplanen</a
          >
        </li>
        <li>
          <a
            href="https://www.aventura-print.de/zipperdisplays-online-bedrucken,category,28882.html"
            >Zipperdisplays</a
          >
        </li>
      </ul>
    </div>
  </aside>
</template>

<script setup lang="ts">
// WarengruppenMenu — keine Props
</script>
